name: "Cache Node and NPM Dependencies"
description: "Caches Node.js dependencies for faster builds"
inputs:
  node-version:
    description: The Node.js version to use.
    default: 20.x
    required: true
  working-directory:
    description: The working directory of the application.
    default: "."
    required: false
runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      working-directory: ${{ inputs.working-directory }}
      with:
        path: ${{ inputs.working-directory }}/node_modules
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: ${{ !steps.cache.outputs.cache-hit }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        npm ci
