name: 01-building-blocks.yaml
on:
  - workflow_dispatch

jobs:
  echo-hello:
   runs-on: ubuntu-latest
   steps:
    - name: Say hello
      run: echo "Hello, World!"

  echo-goodbye:
    runs-on: ubuntu-latest
    name: Say hello
    steps:
    
     - name: Failed step
       run: | 
         echo "I will fail"
         return "404"
       
     - name: Say goodbye
       run: echo "Goodbye!"
