name: 02-workflow-events.yaml
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "The event that triggered the workflow is: ${{ github.event_name }}"