name: 02-workflow-events.yaml
on:
  - schedule:
      - cron: "0 0 * * *"
  - push
  - pull_request
  - workflow_dispatch
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "The event that triggered the workflow is ${{ github.event_name }}"
