name: 04-using-actions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        working-directory: 04-using-actions/react-app
        run: npm install --from-lock-file

      - name: Run Unit Tests
        working-directory: 04-using-actions/react-app
        run: npm run test || exit 0
