name: 12-outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success

jobs:
  check_build_status:
    runs-on: ubuntu-latest
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT"
      - name: Check Build Status
        id: check_status
        run: echo "build_result=${{ inputs.build_result }}" >> $GITHUB_OUTPUT
    outputs:
      final_build_status:
        ${{ steps.check_status.outputs.build_result }}
        #         |    id     |       |    key    |
  execute_deployment:
    runs-on: ubuntu-latest
    needs: check_build_status
    if: ${{ needs.check_build_status.outputs.final_build_status == 'success' }}
    steps: #|       needs           |       |     outputs     |
      - name: Deploy Application
        run: echo "Deploying application..."
