name: 12-outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success

jobs:
  check_build_status:
    runs-on: ubuntu-latest
    outputs:
      final_build_status:
        ${{ steps.check_status.outputs.build_result }}
        #          id     |       |    key    |
      outpu1: ${{ steps.check_status.outputs.output1 }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT"
      - name: Check Build Status
        id: check_status
        run: |
          echo "$GITHUB_OUTPUT"
          echo "build_result=${{ github.event.inputs.build-status }}" >> "$GITHUB_OUTPUT"
          echo "output1=value1" >> "$GITHUB_OUTPUT"
          echo "output2=value2" >> "$GITHUB_OUTPUT"

          cat "$GITHUB_OUTPUT"

  execute_deployment:
    runs-on: ubuntu-latest
    needs: check_build_status
    if: ${{ needs.check_build_status.outputs.final_build_status == 'success' }}
    steps: #|       needs           |       |     outputs     |
      - name: Deploy Application
        run: echo "Deploying application..."
      - name: Print Outputs
        run: echo "${{ needs.check_build_status.outputs.outpu1 }}"
