name: 16 - Working with Environments

run-name: 16 - Working with Environments | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        default: "stating"

jobs:
