name: 17 - 2 - Custom Actions - JS

run-name: 17 - 2 - Custom Actions - JS | ${{ inputs.base-branch }} - ${{ inputs.target-branch }} - ${{ inputs.working-directory }}

on:
  workflow_dispatch:
    inputs:
      base-branch:
        type: string
        default: main
      target-branch:
        type: string
        default: update-dependencies
      working-directory:
        type: string
        default: 17-custom-actions/react-app

jobs:
  dependecy-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for dependencies updates
        uses: ./.github/actions/js-dependecy-update
        with:
          base-branch: ${{ inputs.base-branch }}
          target-branch: ${{ inputs.target-branch }}
          working-directory: ${{ inputs.working-directory }}
