name: 19 - 1 - Managing Concurrency

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on: workflow_dispatch

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/ping-url
        with:
          url: https://imnotvalid-asdasdasdasd.com
          max_trials: 20
          delay: 5
