name: 19 - 2 - Managing Concurrency

on: workflow_dispatch

jobs:
  ping-with-concurrency:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/ping-url
        with:
          url: https://imnotvalid-asdasdasdasd.com
          max_trials: 20
          delay: 5

  ping-without-concurrency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/ping-url
        with:
          url: https://imnotvalid-asdasdasdasd.com
          max_trials: 20
          delay: 5